//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by iocli, run 'iocli gen' to re-generate

package facade

import (
	autowire "github.com/alibaba/ioc-golang/autowire"
	normal "github.com/alibaba/ioc-golang/autowire/normal"
	singleton "github.com/alibaba/ioc-golang/autowire/singleton"
	util "github.com/alibaba/ioc-golang/autowire/util"
)

func init() {
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &keyServiceFacadeCachedImpl_{}
		},
	})
	keyServiceFacadeCachedImplStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &KeyServiceFacadeCachedImpl{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(keyServiceFacadeCachedImplStructDescriptor)
	normal.RegisterStructDescriptor(&autowire.StructDescriptor{
		Factory: func() interface{} {
			return &keyServiceFacadeImpl_{}
		},
	})
	keyServiceFacadeImplStructDescriptor := &autowire.StructDescriptor{
		Factory: func() interface{} {
			return &KeyServiceFacadeImpl{}
		},
		Metadata: map[string]interface{}{
			"aop":      map[string]interface{}{},
			"autowire": map[string]interface{}{},
		},
	}
	singleton.RegisterStructDescriptor(keyServiceFacadeImplStructDescriptor)
}

type keyServiceFacadeCachedImpl_ struct {
	GetById_ func(id int64) (string, error)
}

func (k *keyServiceFacadeCachedImpl_) GetById(id int64) (string, error) {
	return k.GetById_(id)
}

type keyServiceFacadeImpl_ struct {
	GetById_ func(id int64) (string, error)
}

func (k *keyServiceFacadeImpl_) GetById(id int64) (string, error) {
	return k.GetById_(id)
}

type KeyServiceFacadeCachedImplIOCInterface interface {
	GetById(id int64) (string, error)
}

type KeyServiceFacadeImplIOCInterface interface {
	GetById(id int64) (string, error)
}

var _keyServiceFacadeCachedImplSDID string

func GetKeyServiceFacadeCachedImplSingleton() (*KeyServiceFacadeCachedImpl, error) {
	if _keyServiceFacadeCachedImplSDID == "" {
		_keyServiceFacadeCachedImplSDID = util.GetSDIDByStructPtr(new(KeyServiceFacadeCachedImpl))
	}
	i, err := singleton.GetImpl(_keyServiceFacadeCachedImplSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*KeyServiceFacadeCachedImpl)
	return impl, nil
}

func GetKeyServiceFacadeCachedImplIOCInterfaceSingleton() (KeyServiceFacadeCachedImplIOCInterface, error) {
	if _keyServiceFacadeCachedImplSDID == "" {
		_keyServiceFacadeCachedImplSDID = util.GetSDIDByStructPtr(new(KeyServiceFacadeCachedImpl))
	}
	i, err := singleton.GetImplWithProxy(_keyServiceFacadeCachedImplSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(KeyServiceFacadeCachedImplIOCInterface)
	return impl, nil
}

type ThisKeyServiceFacadeCachedImpl struct {
}

func (t *ThisKeyServiceFacadeCachedImpl) This() KeyServiceFacadeCachedImplIOCInterface {
	thisPtr, _ := GetKeyServiceFacadeCachedImplIOCInterfaceSingleton()
	return thisPtr
}

var _keyServiceFacadeImplSDID string

func GetKeyServiceFacadeImplSingleton() (*KeyServiceFacadeImpl, error) {
	if _keyServiceFacadeImplSDID == "" {
		_keyServiceFacadeImplSDID = util.GetSDIDByStructPtr(new(KeyServiceFacadeImpl))
	}
	i, err := singleton.GetImpl(_keyServiceFacadeImplSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(*KeyServiceFacadeImpl)
	return impl, nil
}

func GetKeyServiceFacadeImplIOCInterfaceSingleton() (KeyServiceFacadeImplIOCInterface, error) {
	if _keyServiceFacadeImplSDID == "" {
		_keyServiceFacadeImplSDID = util.GetSDIDByStructPtr(new(KeyServiceFacadeImpl))
	}
	i, err := singleton.GetImplWithProxy(_keyServiceFacadeImplSDID, nil)
	if err != nil {
		return nil, err
	}
	impl := i.(KeyServiceFacadeImplIOCInterface)
	return impl, nil
}

type ThisKeyServiceFacadeImpl struct {
}

func (t *ThisKeyServiceFacadeImpl) This() KeyServiceFacadeImplIOCInterface {
	thisPtr, _ := GetKeyServiceFacadeImplIOCInterfaceSingleton()
	return thisPtr
}
